###########################################################################
# Properties file for the log4j logger system
#log4j.rootCategory=INFO, logFile
#
#
###########################################################################
# Setup a rolling file appender
#
#log4j.appender.logFile=org.apache.log4j.RollingFileAppender
#
#
###########################################################################
# Use the following appender to send messages go to stdout (System.out)
#
# log4j.appender.logFile=org.apache.log4j.ConsoleAppender
#
#
# Use the following appender to write to a file.
# Relative file names will be relative to the directory specified by the
# user.dir System property.
# WARNING: ALL SLASHES MUST BE FORWARD SLASHES OR ESCAPED BACK SLASHES!!!
#
# log4j.appender.logFile.File=d:/mboyd/time/trax.log
#
#
# This tells log4j what type of encoding to use
#
# log4j.appender.logFile.Encoding=UTF-8
#
#
# This is the maximum size that the portal log file will grow before being rolled
#
# log4j.appender.logFile.MaxFileSize=3000KB
#
#
# This is the maximum number of rolled log files that will be maintained
#
# log4j.appender.logFile.MaxBackupIndex=10
#
# This tells log4j to use PatternLayout for log file formatting
#
# log4j.appender.logFile.layout=org.apache.log4j.PatternLayout
#
#
# Pattern used during debugging
#
# log4j.appender.logFile.layout.ConversionPattern=%5p [%t] %c{2}.[%x] (%F:%L) %d{MMM/dd HH:mm:ss} - %m%n
#
#
# Pattern that should be used when speed is important (it doesn't provide location info)
#
# log4j.appender.logFile.layout.ConversionPattern=%5p [%t] %c{2}.[%x] %d{MMM/dd HH:mm:ss} - %m%n
#


log4j.appender.logFile=org.apache.log4j.RollingFileAppender
log4j.appender.logFile.File=./logs/launch.log
log4j.appender.logFile.Encoding=UTF-8
log4j.appender.logFile.MaxFileSize=3000KB
log4j.appender.logFile.MaxBackupIndex=10
log4j.appender.logFile.layout=org.apache.log4j.PatternLayout
log4j.appender.logFile.layout.ConversionPattern=%5p [%t] %c{2}.[%x] (%F:%L) %d{MMM/dd HH:mm:ss} - %m%n


log4j.rootCategory=ERROR, logFile


#log4j.appender.mboyd=org.apache.log4j.RollingFileAppender
#log4j.appender.mboyd.File=mboyd.log
#log4j.appender.mboyd.MaxFileSize=1000KB
#log4j.appender.mboyd.MaxBackupIndex=10
#log4j.appender.mboyd.layout=org.apache.log4j.PatternLayout
#log4j.appender.mboyd.layout.ConversionPattern=%5p [%t] %c{2}.[%x] (%F:%L) %d{MMM/dd HH:mm:ss} - %m%n
#log4j.logger.org.jasig.portal.car=DEBUG, mboyd
#log4j.logger.org.jasig.portal.UserInstance=DEBUG, mboyd
#log4j.logger.org.jasig.portal.layout.dlm=DEBUG, mboyd
#log4j.logger.org.jasig.portal.channels.DLMUserPreferences=INFO, mboyd
#log4j.logger.org.jasig.portal.channels.jsp.Channel=DEBUG, mboyd
#log4j.logger.org.jasig.portal.channels.jsp.ServantChannel=DEBUG, mboyd
#log4j.logger.org.jasig.portal.i18n.channels.resedit.Controller=DEBUG, mboyd

log4j.logger.nbdp.trax.report.R_TimeCompositeByTask=DEBUG, logFile
log4j.logger.nbdp.trax.TimelineView=DEBUG
log4j.logger.nbdp.trax.Launch=DEBUG
log4j.logger.nbdp.ltrax=DEBUG
